### ISSUE TITLE
Dont know how to install

### ISSUE THREAD

**Issue by huzijian1996** [erniejunior/QuadrotorEnvironment#1]
I am a newer of python and ubuntu. I am interested in your env. Could u pls give me a tutorial for how to install ?

**Comment by huzijian1996** [comment]
Actually,the problem is that I could not find the file named quadrotor_rl_code.

**Comment by ernestum** [comment]
This is just a very early release. I plan to release a more polished version with lots of bug-fixes and better documentation in the coming weeks. Sorry but I do not have time for that right now. For any future requests please include at least the stack trace or some way on how to reproduce your problem.

**Comment by ernestum** [comment]
Hey @imHZjian1996 I uploaded a new version with a travis script. Maybe it is now easier to use for your?

**Comment by ernestum** [comment]
Now there is a setup.py script. So if you are in the root directory of the project something like
```bash
$ pip3 install --user .
```
Should work.

**Comment by ernestum** [comment]
Look at the readme now. That should be enough.
